can uninstall now

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,4 +1,25 @@
 #!/bin/bash
+function s_uninstall()
+{
+    [ -r s_u_install.lst ] && xargs rm < s_u_install.lst &> /dev/null && rm s_u_install.lst
+    if ! [ -r s_u_vars.lst ] ;then
+	echo "cannot find s_u_vars.lst"
+	exit
+    fi	
+    {
+	read S_INSTALL_DIST
+	read S_BASH_RC
+    } < s_u_vars.lst
+    begin=$(grep -n '^##\^\^' ${S_BASH_RC} |  cut -d: -f1 | head -1)
+    end=$(grep -n '^##\$\$' ${S_BASH_RC} |  cut -d: -f1 | head -1)
+    if [ "$begin" -lt "$end" ] &> /dev/null ;then
+	mv ${S_BASH_RC} ${S_BASH_RC}~
+	awk "NR < ${begin} || NR > ${end}" < ${S_BASH_RC}~ > ${S_BASH_RC} && rm s_u_vars.lst
+    else
+	echo "you may need to clear bashrc manually"
+    fi
+}
+
 for ((i = 1;i <= $#;i++)) ;do
     case ${!i} in
 	-t)
@@ -10,6 +31,11 @@ for ((i = 1;i <= $#;i++)) ;do
 	    shift $i
 	    S_BASH_RC=${!i}
 	    shift $i
+	    ;;
+	-u)
+	    shift $i
+	    s_uninstall
+	    exit
 	    ;;
     esac
 done
@@ -30,7 +56,12 @@ if [ "$S_BASH_RC" = "" ] ;then
     fi
 fi
 
-for file in $(find ! -regex '\./install' -and ! -name '.*' -and ! -regex '.*/\.[^/]*/.*') ;do
+rm *.lst &> /dev/null
+
+echo "${S_INSTALL_DIST}" >> s_u_vars.lst
+echo "${S_BASH_RC}" >> s_u_vars.lst
+
+for file in $(find ! -regex '\./install' -and ! -name '.*' -and ! -regex '.*/\.[^/]*/.*' -and ! -regex '.*\.lst' -and ! -regex '\./README') ;do
     if [ "$file" = "./setup.sh" ] ;then
 	sed -e "s:@@install_dir:${S_INSTALL_DIST}:g" < "${file}" > ${S_INSTALL_DIST}/setup.sh
 	chmod 644 ${S_INSTALL_DIST}/setup.sh
@@ -46,7 +77,9 @@ for file in $(find ! -regex '\./install' -and ! -name '.*' -and ! -regex '.*/\.[
     echo "${S_INSTALL_DIST}/${file}" >> s_u_install.lst
 done
 
+if [ $(tail -n1 ${S_BASH_RC} | wc -l) = 0 ] ;then
+    echo >> ${S_BASH_RC}
+fi
 echo '##^^this part is generate automatically when installing' >> ${S_BASH_RC}
 echo "[ -r ${S_INSTALL_DIST}/setup.sh ] && . ${S_INSTALL_DIST}/setup.sh" >> ${S_BASH_RC}
 echo '##$$end' >> ${S_BASH_RC}
-
