tab to space

diff --git a/install b/install
--- a/install
+++ b/install
@@ -4,7 +4,7 @@ post_instl()
 {
     local S_BASH_RC="$1" S_INSTALL_DIST="$2"
     if [ $(tail -n1 ${S_BASH_RC} | wc -l) = 0 ] ;then
-	echo >> ${S_BASH_RC}
+        echo >> ${S_BASH_RC}
     fi &&
     echo '##^^this part is generate automatically when installing' >> ${S_BASH_RC} &&
     echo "[ -r ${S_INSTALL_DIST}/setup.sh ] && . ${S_INSTALL_DIST}/setup.sh" >> ${S_BASH_RC} &&
@@ -17,23 +17,23 @@ pre_rm()
     local varlst=${s_util_dir}/vars.lst
 
     [ -r "${varlst}" ] || {
-	echo "error: cannot find ${varlst}"
-	exit 1
+        echo "error: cannot find ${varlst}"
+        exit 1
     }
 
     local S_INSTALL_DIST S_BASH_RC
 
     {
-	read S_INSTALL_DIST
-	read S_BASH_RC
+        read S_INSTALL_DIST
+        read S_BASH_RC
     } < "${varlst}" &&
     begin=$(grep -n '^##\^\^' ${S_BASH_RC} |  cut -d: -f1 | head -1) &&
     end=$(grep -n '^##\$\$' ${S_BASH_RC} |  cut -d: -f1 | head -1) &&
     [ "$begin" -lt "$end" ] &&
     mv ${S_BASH_RC} ${S_BASH_RC}~ &&
     awk "NR < ${begin} || NR > ${end}" < ${S_BASH_RC}~ > ${S_BASH_RC} || {
-	echo "warning: you may need to clear bashrc manually" >&2
-	exit 0
+        echo "warning: you may need to clear bashrc manually" >&2
+        exit 0
     }
 }
 
@@ -41,39 +41,39 @@ prefix=""
 
 for ((i = 1;i <= $#;i++)) ;do
     case ${!i} in
-	--post_instl)
-	    declare -f post_instl
-	    exit 0
-	    ;;
-	--pre_rm)
-	    declare -f pre_rm
-	    exit 0
-	    ;;
-	-t|--to)
-	    let 'i++'
-	    S_INSTALL_DIST=${!i}
-	    ;;
-	-r|--rc)
-	    let 'i++'
-	    S_BASH_RC=${!i}
-	    ;;
-	-p|--prefix)
-	    let 'i++'
-	    prefix=${!i}
-	    ;;
-	--no-uninstall)
-	    n_uinstl=1
-	    ;;
-	--force-usr)
-	    force_usr=1
-	    ;;
-	--nopstinstl)
-	    nopstinstl=1
-	    ;;
-	*)
-	    echo "error: unrecognized argument ${!i}" >&2
-	    exit 1
-	    ;;
+        --post_instl)
+            declare -f post_instl
+            exit 0
+            ;;
+        --pre_rm)
+            declare -f pre_rm
+            exit 0
+            ;;
+        -t|--to)
+            let 'i++'
+            S_INSTALL_DIST=${!i}
+            ;;
+        -r|--rc)
+            let 'i++'
+            S_BASH_RC=${!i}
+            ;;
+        -p|--prefix)
+            let 'i++'
+            prefix=${!i}
+            ;;
+        --no-uninstall)
+            n_uinstl=1
+            ;;
+        --force-usr)
+            force_usr=1
+            ;;
+        --nopstinstl)
+            nopstinstl=1
+            ;;
+        *)
+            echo "error: unrecognized argument ${!i}" >&2
+            exit 1
+            ;;
     esac
 done
 
@@ -124,10 +124,10 @@ cat /dev/null | tee "${filelst}" | tee "${cmdlst}"
 
 for file in $(for ((i = 0;i < ${#ignore[@]};i++)) ;do ((i == 0)) || echo '-and'; echo '! -regex'; echo "${ignore[i]}";done | xargs find -type f) ;do
     if [[ $file =~ $notcmd ]] ;then
-	install -m644 ${file} ${S_INSTALL_DIST}/${file} &&
-	echo "${_S_INSTALL_DIST}/${file}" >> "${filelst}" ||
-	exit 1
-	continue
+        install -m644 ${file} ${S_INSTALL_DIST}/${file} &&
+        echo "${_S_INSTALL_DIST}/${file}" >> "${filelst}" ||
+        exit 1
+        continue
     fi
     install -m755 ${file} ${S_INSTALL_DIST}/${file} &&
     echo "${_S_INSTALL_DIST}/${file}" >> "${filelst}" &&
diff --git a/lsutil b/lsutil
--- a/lsutil
+++ b/lsutil
@@ -4,11 +4,11 @@ s_shelp()
     cat<<EOF
 This command list the favorate commands names.
 USAGE:
-	$(basename $0) [OPTIONS] [command]
+        $(basename $0) [OPTIONS] [command]
 OPTIONS:
-	-v/--version: show the version number and exit
-	-h/--help: show this help and exit
-	
+        -v/--version: show the version number and exit
+        -h/--help: show this help and exit
+
 EOF
 }
 
@@ -31,7 +31,7 @@ del_frm_ary()
     local __n=${#__tmp_array[@]}
     local i
     for ((i = 0;i < __n;i++)) ;do
-	[[ ${__key} == ${__tmp_array[i]} ]] && unset __tmp_array[i]
+        [[ ${__key} == ${__tmp_array[i]} ]] && unset __tmp_array[i]
     done
     eval "${__array}"'=("${__tmp_array[@]}")'
 }
@@ -57,33 +57,33 @@ usr_cmd_lst="${usr_conf_dir}/bkmrk.lst"
 
 for ((i = 0;i < ${#args[@]};)) ;do
     case "${args[i]}" in
-	-a|--add)
-	    darg $i
-	    [[ ${args[i]} =~ ^! ]] && {
-		echo "command cannot start with !"
-		exit 1
-	    }
-	    if [ $(tail -n1 ${usr_cmd_lst} | wc -l) = 0 ] ;then
-		echo >> ${usr_cmd_lst}
-	    fi &&
-	    echo "${args[i]}" >> ${usr_cmd_lst} || exit 1
-	    exit 0
-	    ;;
-	-d|--delete)
-	    darg $i
-	    [[ ${args[i]} =~ ^! ]] && {
-		echo "command cannot start with !"
-		exit 1
-	    }
-	    if [ $(tail -n1 ${usr_cmd_lst} | wc -l) = 0 ] ;then
-		echo >> ${usr_cmd_lst}
-	    fi &&
-	    echo "!${args[i]}" >> ${usr_cmd_lst} || exit 1
-	    exit 0
-	    ;;
-	*)
-	    let 'i++'
-	    ;;
+        -a|--add)
+            darg $i
+            [[ ${args[i]} =~ ^! ]] && {
+                echo "command cannot start with !"
+                exit 1
+            }
+            if [ $(tail -n1 ${usr_cmd_lst} | wc -l) = 0 ] ;then
+                echo >> ${usr_cmd_lst}
+            fi &&
+            echo "${args[i]}" >> ${usr_cmd_lst} || exit 1
+            exit 0
+            ;;
+        -d|--delete)
+            darg $i
+            [[ ${args[i]} =~ ^! ]] && {
+                echo "command cannot start with !"
+                exit 1
+            }
+            if [ $(tail -n1 ${usr_cmd_lst} | wc -l) = 0 ] ;then
+                echo >> ${usr_cmd_lst}
+            fi &&
+            echo "!${args[i]}" >> ${usr_cmd_lst} || exit 1
+            exit 0
+            ;;
+        *)
+            let 'i++'
+            ;;
     esac
 done
 
@@ -97,9 +97,9 @@ favolst=()
 
 for ((i = 0;i < ${#cmdlst[@]};i++)) ;do
     if [[ ${cmdlst[i]} =~ ^! ]] ;then
-	del_frm_ary "${cmdlst[i]#!}" favolst
+        del_frm_ary "${cmdlst[i]#!}" favolst
     else
-	apnd_to_ary "${cmdlst[i]}" favolst
+        apnd_to_ary "${cmdlst[i]}" favolst
     fi
 done
 
